### PR TITLE
use env variable for script copy location

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by jhadvig** [comment]
Since the `STI_SCRIPTS_PATH` is set to `image:///usr/local/sti`, which is on a proper PATH this won't work.

**Comment by bparees** [comment]
@jhadvig see https://github.com/openshift/sti-base/pull/60/files#diff-b0556bed298b3a4fb269eb10d69c91a5R14

**Comment by bparees** [comment]
STI_SCRIPTS_PATH!=STI_SCRIPTS_URL

**Comment by jhadvig** [comment]
LGTM

**Pull request merged**
