### PR TITLE
merge env and run commands to reduce layers

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mnagy does this failure mean anything to you?
Installing App::cpanminus (1.7033)
Couldn't require CPANPLUS::Dist::Build : Can't locate CPANPLUS/Dist/Build/Constants.pm in @INC (@INC contains: /opt/rh/perl516/root/usr/local/lib64/perl5 /opt/rh/perl516/root/usr/local/share/perl5 /opt/rh/perl516/root/usr/lib64/perl5/vendor_perl /opt/rh/perl516/root/usr/share/perl5/vendor_perl /opt/rh/perl516/root/usr/lib64/perl5 /opt/rh/perl516/root/usr/share/perl5 .) at /opt/rh/perl516/root/usr/share/perl5/CPANPLUS/Dist/Build.pm line 14.
BEGIN failed--compilation aborted at /opt/rh/perl516/root/usr/share/perl5/CPANPLUS/Dist/Build.pm line 17.
Compilation failed in require at (eval 58) line 2.

from:
https://ci.openshift.redhat.com/jenkins/job/sti-perl/10/console

**Comment by mnagy** [comment]
@bparees Yes, it does ring a bell. I don't understand what's wrong there, but it always worked for me anyway.

The problem is somewhere else. PATH is apparently not set properly. `cpanm` should be installed into `/opt/rh/perl516/root/usr/local/bin/` but `which` does not look there.

**Comment by mnagy** [comment]
@bparees it was a bug in the downgraded Docker. Per @mfojtik's recommendations, I commented out the downgrade bit, since we don't push perl anyway and rerun the build. Seems like it's working fine now.

**Comment by mnagy** [comment]
LGTM, but be aware that this will conflict with #7.

**Comment by bparees** [comment]
@mnagy @mfojtik awesome, thanks!

**Pull request merged**
