### PR TITLE
Remove source of .bashrc

### PR DESCRIPTION
**Pull request by mnagy**
The sti base image will take care of it through BASH_ENV.

This depends on https://github.com/openshift/sti-base/pull/33

### CODE REVIEW

**Comment by mnagy** [comment]
@mfojtik

**Comment by mfojtik** [comment]
have to be tested with perl-ex, nodejs-ex, rails-ex and php example.

**Comment by mnagy** [comment]
@mfojtik where do those live? sti-perl has a test included

**Comment by jhadvig** [comment]
@mnagy we dont have tests for the *-ex application, you will probably need to test the changed images manually.

**Pull request closed without merging**
