### PR TITLE
Randomize the UID for container that run the test

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
https://github.com/openshift/sti-base/issues/44

**Comment by mnagy** [comment]
I think we should test it with the default user as well, not just a "randomized" uid.

**Comment by mfojtik** [comment]
@mnagy what is the point of doing that? 'default' user is another 'random' user ;-)

**Comment by mnagy** [comment]
@mfojtik Technically yes, but I think I'd be nice to cover the docker use-case of not using a --user flag to make sure that the default uids work.

**Comment by mfojtik** [comment]
@mnagy i don't want to make our tests run longer just to prove that 'default' user will behave same as random user. The random user naturally has less privileges than default and we care only about random user here. If random user can't run the app, then we are broken. If that happens, we don't care if 'default' user has the same problem or not.

**Comment by mnagy** [comment]
@mfojtik ok, I take that back. One more reason I had was that I thought we were doing some "default user" stuff in docker files, but I just realized that we do that in DB images.

LGTM

**Pull request merged**
