### PR TITLE
install gd-devel package

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift/sti-perl/issues/68

### CODE REVIEW

**Comment by bparees** [comment]
@nhr ptal

**Comment by ppisar** [comment]
I'm against this commit. There is no reason why to install exactly this package. In general I'm against adding arbitrary package.

**Comment by ppisar** [comment]
If you want put this OpenShift work around somewhere, put into base image. The gd requirement is nothing specific to Perl. You can have the same request in PHP, Python etc.

**Comment by bparees** [comment]
@ppisar some packages are more commonly used by some frameworks than others.  eg imagemagick is a common php dep, even though it's not a php package, so i would install that in the php image, not the base image, at least as a starting point.

Whether this package falls in that category or not i'm less sure since i'm not a perl dev.

I'm ok w/ putting it in the base image instead, but first i'd like a little more confirmation that it is indeed commonly used by php/ruby/python/nodejs.

**Comment by bparees** [comment]
this has been requested for python also so we'll add it to sti-base.

**Pull request closed without merging**
