### PR TITLE
Support running Perl containers with a random uid

### PR DESCRIPTION
**Pull request by csrwng**
Makes it possible to run resulting images using any uid

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees - changes here are similar to the ones in the php image. ptal.

**Comment by bparees** [comment]
ok to test

**Comment by bparees** [comment]
add to whitelist

**Comment by bparees** [comment]
lgtm, pending test results (if we can get the thing to test it)

**Comment by bparees** [comment]
@csrwng humor me and close this PR and open it as a new one (make sure it gets a new PR#).  I think maybe i fixed the issue.

**Pull request closed without merging**
