### PR TITLE
revert logging stderr to stdout.

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik @ppisar @hhorak ptal, this reverts the stderr logging behavior for now because we need docker1.8 compatibility for OSE.

**Comment by bparees** [comment]
(intentionally left as separate commits for easer re-reversion in the future, we will want to retain the typo fixes)

**Comment by mnagy** [comment]
Why do you revert typo fixes and applying them back? Can't you just revert two commits?

**Comment by bparees** [comment]
no because the typo fix commit causes conflicts that prevent reverting the other commits.  or my git-fu is weak.

**Comment by mnagy** [comment]
I've only seen one conflict with the 5.20/test/run command. You can just resolve it manually, add it and commit. Then you'll end up with just two revert commits.

**Comment by bparees** [comment]
@mnagy if you have a better approach, please just create the pull.

**Comment by mnagy** [comment]
Done: https://github.com/openshift/sti-perl/pull/77

**Comment by ppisar** [comment]
Please consider my pull request #78 instead fo mfojtik's #77.

**Pull request closed without merging**
