### PR TITLE
Move installation of cpanm to assemble

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees @mnagy PTAL

**Comment by mfojtik** [comment]
Locked to 1.7102 which is latest stable released version.

**Comment by bparees** [comment]
lgtm.

**Comment by mfojtik** [comment]
@hhorak FYI

Just to clarify this... This is not a problem-solver, just temporary workaround before we get RPM package we can use. Having this installation in assemble make us responsible for fixing security bugs along other things.

**Pull request merged**
